"""f3 cobranza_factura pago_cliente requisicion movimiento_bancario

4 tablas nuevas de F3 (Cobranza y Pagos): `movimiento_bancario`, `cobranza_factura`,
`pago_cliente`, `requisicion`. Ninguna tabla de F0/F1/F2 se toca.

`--autogenerate` también detectó una desviación de índices PREEXISTENTE, ajena a F3
(`uq_constantes_sistema_grupo_clave`, `ix_contrato_estado_contrato`,
`ix_marca_nombre_marca` — la misma que ya reportaba `alembic check` antes de este
módulo). Se quitó a mano del `upgrade()`/`downgrade()` generados: mezclar esa deriva
con las tablas nuevas de F3 en el mismo archivo habría hecho ilegible el propósito de
la migración y complicado revertirla si algo de F3 fallara. Queda pendiente su propia
migración por separado.

Revision ID: 4235d887cf06
Revises: a9b3cdeef9e7
Create Date: 2026-09-09 20:43:05.238933
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# identificadores de revisión, usados por Alembic.
revision: str = '4235d887cf06'
down_revision: str | None = 'a9b3cdeef9e7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimiento_bancario',
    sa.Column('movimiento_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_movimiento', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=False),
    sa.Column('tipo_movimiento', sa.Unicode(length=20), nullable=False),
    sa.Column('monto_movimiento', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('referencia_bancaria', sa.Unicode(length=100), nullable=True),
    sa.Column('descripcion_movimiento', sa.Unicode(length=300), nullable=True),
    sa.Column('conciliado', sa.Boolean(), nullable=False),
    sa.Column('archivo_nombre', sa.Unicode(length=255), nullable=True),
    sa.Column('archivo_path', sa.Unicode(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.CheckConstraint("tipo_movimiento IN ('cargo', 'abono')", name='ck_movimiento_bancario_tipo'),
    sa.CheckConstraint('monto_movimiento > 0', name='ck_movimiento_bancario_monto'),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario_id'], name='fk_movimiento_bancario_created_by', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('movimiento_id')
    )
    op.create_table('cobranza_factura',
    sa.Column('cobranza_id', sa.Uuid(), nullable=False),
    sa.Column('factura_id', sa.Uuid(), nullable=False),
    sa.Column('anunciante_id', sa.Uuid(), nullable=False),
    sa.Column('metodo_pago_clave', sa.Unicode(length=20), nullable=False),
    sa.Column('dias_credito', sa.Integer(), nullable=False),
    sa.Column('fecha_estimada_cobro', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=False),
    sa.Column('fecha_cobro', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=True),
    sa.Column('estatus_cobro', sa.Unicode(length=20), nullable=False),
    sa.Column('comentarios_cobranza', sa.UnicodeText().with_variant(sa.NVARCHAR(), 'mssql'), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("estatus_cobro IN ('pendiente', 'cobro_parcial', 'cobrada')", name='ck_cobranza_factura_estatus'),
    sa.CheckConstraint('dias_credito >= 0', name='ck_cobranza_factura_dias_credito'),
    sa.ForeignKeyConstraint(['anunciante_id'], ['anunciante.anunciante_id'], name='fk_cobranza_factura_anunciante'),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario_id'], name='fk_cobranza_factura_created_by', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['factura_id'], ['factura_cliente.factura_id'], name='fk_cobranza_factura_factura', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('cobranza_id'),
    sa.UniqueConstraint('factura_id')
    )
    op.create_table('pago_cliente',
    sa.Column('pago_cliente_id', sa.Uuid(), nullable=False),
    sa.Column('cobranza_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_pago_cliente', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=False),
    sa.Column('monto_aplicado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('metodo_pago_clave', sa.Unicode(length=20), nullable=False),
    sa.Column('referencia_pago', sa.Unicode(length=100), nullable=True),
    sa.Column('archivo_nombre', sa.Unicode(length=255), nullable=True),
    sa.Column('archivo_path', sa.Unicode(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.CheckConstraint('monto_aplicado > 0', name='ck_pago_cliente_monto'),
    sa.ForeignKeyConstraint(['cobranza_id'], ['cobranza_factura.cobranza_id'], name='fk_pago_cliente_cobranza', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario_id'], name='fk_pago_cliente_created_by', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('pago_cliente_id')
    )
    op.create_index(op.f('ix_pago_cliente_cobranza_id'), 'pago_cliente', ['cobranza_id'], unique=False)
    op.create_table('requisicion',
    sa.Column('requisicion_id', sa.Uuid(), nullable=False),
    sa.Column('numero_requisicion', sa.Unicode(length=30), nullable=False),
    sa.Column('numero_oc_sap', sa.Unicode(length=30), nullable=True),
    sa.Column('tipo_requisicion', sa.Unicode(length=20), nullable=False),
    sa.Column('factura_afiliado_id', sa.Uuid(), nullable=True),
    sa.Column('factura_agencia_id', sa.Uuid(), nullable=True),
    sa.Column('orden_id', sa.Uuid(), nullable=True),
    sa.Column('afiliado_id', sa.Uuid(), nullable=True),
    sa.Column('agencia_id', sa.Uuid(), nullable=True),
    sa.Column('vendedor_comision_id', sa.Uuid(), nullable=True),
    sa.Column('razon_social_afiliada', sa.Unicode(length=200), nullable=True),
    sa.Column('monto_requisicion', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('porcentaje_comision_vendedor', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requisicion_comision_vendedor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('porcentaje_comision_agencia_req', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('requisicion_comision_agencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('diferencia_afiliada', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('estatus_requisicion', sa.Unicode(length=20), nullable=False),
    sa.Column('fecha_pago_requisicion', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=True),
    sa.Column('observaciones_cuentas_por_pagar', sa.UnicodeText().with_variant(sa.NVARCHAR(), 'mssql'), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("estatus_requisicion IN ('pendiente', 'autorizada', 'pagada', 'cancelada')", name='ck_requisicion_estatus'),
    sa.CheckConstraint("tipo_requisicion IN ('pago_afiliado', 'pago_agencia', 'comision_vendedor', 'comision_agencia')", name='ck_requisicion_tipo'),
    sa.CheckConstraint('monto_requisicion >= 0', name='ck_requisicion_monto'),
    sa.ForeignKeyConstraint(['afiliado_id'], ['afiliado.afiliado_id'], name='fk_requisicion_afiliado', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['agencia_id'], ['agencia.agencia_id'], name='fk_requisicion_agencia', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario_id'], name='fk_requisicion_created_by', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['factura_afiliado_id'], ['factura_afiliado.factura_afiliado_id'], name='fk_requisicion_factura_afiliado', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['factura_agencia_id'], ['factura_agencia.factura_agencia_id'], name='fk_requisicion_factura_agencia', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_cliente.orden_id'], name='fk_requisicion_orden', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['vendedor_comision_id'], ['vendedor.vendedor_id'], name='fk_requisicion_vendedor', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('requisicion_id')
    )
    # ### end Alembic commands ###
    # (se quitó a mano la deriva preexistente de índices de constantes_sistema/contrato/
    # marca que `--autogenerate` detectó de paso — ver docstring del módulo, ajena a F3)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisicion')
    op.drop_index(op.f('ix_pago_cliente_cobranza_id'), table_name='pago_cliente')
    op.drop_table('pago_cliente')
    op.drop_table('cobranza_factura')
    op.drop_table('movimiento_bancario')
    # ### end Alembic commands ###
