"""f2 facturacion factura_cliente afiliado agencia costo_adicional

Revision ID: 3e57e45d24cb
Revises: a1c8e3d47b92
Create Date: 2026-08-24 16:59

Crea las 5 tablas de la FASE 2 de la spec BD v2. NINGUNA tabla de F0/F1 se toca.

ADVERTENCIA — leer antes de tocar este archivo (mismo criterio que la migración de F1):
mientras esta revisión NO se haya aplicado a RDS, es seguro editarla en sitio. En el
momento en que se aplique a RDS por primera vez, esa ventana se cierra: cualquier cambio
posterior al esquema va en una migración NUEVA encadenada, nunca editando esta.

NOTA sobre el autogenerate: la corrida original propuso además 4 operaciones sobre
tablas de F0 (índice/unique de `constantes_sistema`, índice de `contrato`, índice de
`marca`). Son deriva PREEXISTENTE entre los modelos y la base, ajena a F2 y sobre tablas
ya aplicadas a RDS — se eliminaron a mano de este archivo. Queda anotado como ticket
aparte, no como descuido.

Dos desviaciones aditivas aprobadas respecto a la spec (ver ficha del módulo):
`layout_factura` (texto libre nullable, sin catálogo LayoutFactura) y `metodo_pago_clave`
(texto sin FK; `MetodoPago` vive en `ConstantesSistema`). `updated_at` también es aditivo
en `factura_afiliado`/`factura_agencia`/`costo_adicional` (CLAUDE.md §6, precedente F1).

Los CHECK de igualdad de montos llevan `ROUND(x, 2)` en AMBOS lados (ADR-039): en SQLite
`NUMERIC` se guarda como float64 y una suma puede diferir por 1 ULP; en SQL Server
`NUMERIC(14,2)` es de punto fijo y `ROUND` es un no-op inofensivo.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# identificadores de revisión, usados por Alembic.
revision: str = '3e57e45d24cb'
down_revision: str | None = 'a1c8e3d47b92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factura_afiliado',
    sa.Column('factura_afiliado_id', sa.Uuid(), nullable=False),
    sa.Column('afiliado_id', sa.Uuid(), nullable=False),
    sa.Column('razon_social_afiliada', sa.Unicode(length=200), nullable=True),
    sa.Column('factura_emisora', sa.Unicode(length=50), nullable=False),
    sa.Column('fecha_factura_afiliado', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=False),
    sa.Column('monto_factura_afiliado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva_factura_afiliado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_factura_afiliado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('archivo_nombre', sa.Unicode(length=255), nullable=True),
    sa.Column('archivo_path', sa.Unicode(length=500), nullable=True),
    sa.Column('estatus_factura_afiliado', sa.Unicode(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("estatus_factura_afiliado IN ('recibida', 'en_revision', 'autorizada', 'pagada')", name='ck_factura_afiliado_estatus'),
    sa.CheckConstraint('ROUND(total_factura_afiliado, 2) = ROUND(monto_factura_afiliado + iva_factura_afiliado, 2)', name='ck_factura_afiliado_total_suma'),
    sa.CheckConstraint('iva_factura_afiliado >= 0', name='ck_factura_afiliado_iva'),
    sa.CheckConstraint('monto_factura_afiliado >= 0', name='ck_factura_afiliado_monto'),
    sa.CheckConstraint('total_factura_afiliado >= 0', name='ck_factura_afiliado_total'),
    sa.ForeignKeyConstraint(['afiliado_id'], ['afiliado.afiliado_id'], name='fk_factura_afiliado_afiliado', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario_id'], name='fk_factura_afiliado_created_by', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('factura_afiliado_id')
    )
    op.create_table('costo_adicional',
    sa.Column('costo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_costo', sa.Unicode(length=20), nullable=False),
    sa.Column('orden_id', sa.Uuid(), nullable=True),
    sa.Column('descripcion_costo', sa.Unicode(length=300), nullable=False),
    sa.Column('periodo_contable', sa.Unicode(length=7), nullable=False),
    sa.Column('monto_costo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('archivo_nombre', sa.Unicode(length=255), nullable=True),
    sa.Column('archivo_path', sa.Unicode(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("periodo_contable LIKE '____-__'", name='ck_costo_adicional_periodo'),
    sa.CheckConstraint("tipo_costo IN ('nomina', 'overhead')", name='ck_costo_adicional_tipo'),
    sa.CheckConstraint('monto_costo >= 0', name='ck_costo_adicional_monto'),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario_id'], name='fk_costo_adicional_created_by', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_cliente.orden_id'], name='fk_costo_adicional_orden', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('costo_id')
    )
    op.create_table('factura_agencia',
    sa.Column('factura_agencia_id', sa.Uuid(), nullable=False),
    sa.Column('agencia_id', sa.Uuid(), nullable=False),
    sa.Column('orden_id', sa.Uuid(), nullable=False),
    sa.Column('folio_factura_agencia', sa.Unicode(length=50), nullable=True),
    sa.Column('fecha_factura_agencia', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=False),
    sa.Column('monto_factura_agencia', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva_factura_agencia', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_factura_agencia', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('porcentaje_comision_agencia', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comision_agencia', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('archivo_nombre', sa.Unicode(length=255), nullable=True),
    sa.Column('archivo_path', sa.Unicode(length=500), nullable=True),
    sa.Column('estatus_factura_agencia', sa.Unicode(length=20), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("estatus_factura_agencia IN ('recibida', 'en_revision', 'autorizada', 'pagada')", name='ck_factura_agencia_estatus'),
    sa.CheckConstraint('ROUND(total_factura_agencia, 2) = ROUND(monto_factura_agencia + iva_factura_agencia, 2)', name='ck_factura_agencia_total_suma'),
    sa.CheckConstraint('comision_agencia >= 0', name='ck_factura_agencia_comision'),
    sa.CheckConstraint('iva_factura_agencia >= 0', name='ck_factura_agencia_iva'),
    sa.CheckConstraint('monto_factura_agencia >= 0', name='ck_factura_agencia_monto'),
    sa.CheckConstraint('porcentaje_comision_agencia >= 0 AND porcentaje_comision_agencia <= 100', name='ck_factura_agencia_pct_comision'),
    sa.CheckConstraint('total_factura_agencia >= 0', name='ck_factura_agencia_total'),
    sa.ForeignKeyConstraint(['agencia_id'], ['agencia.agencia_id'], name='fk_factura_agencia_agencia', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario_id'], name='fk_factura_agencia_created_by', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_cliente.orden_id'], name='fk_factura_agencia_orden', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('factura_agencia_id')
    )
    op.create_table('factura_cliente',
    sa.Column('factura_id', sa.Uuid(), nullable=False),
    sa.Column('numero_factura', sa.Unicode(length=30), nullable=False),
    sa.Column('numero_pedido', sa.Unicode(length=50), nullable=True),
    sa.Column('referencia_adicional', sa.Unicode(length=150), nullable=True),
    sa.Column('orden_id', sa.Uuid(), nullable=False),
    sa.Column('factura_relacionada_id', sa.Uuid(), nullable=True),
    sa.Column('empresa_facturadora_id', sa.Uuid(), nullable=False),
    sa.Column('anunciante_id', sa.Uuid(), nullable=False),
    sa.Column('agencia_id', sa.Uuid(), nullable=True),
    sa.Column('razon_social_facturacion', sa.Unicode(length=200), nullable=False),
    sa.Column('rfc_facturacion', sa.Unicode(length=13), nullable=False),
    sa.Column('direccion_facturacion', sa.UnicodeText().with_variant(sa.NVARCHAR(), 'mssql'), nullable=True),
    sa.Column('descripcion_factura', sa.UnicodeText().with_variant(sa.NVARCHAR(), 'mssql'), nullable=False),
    sa.Column('observaciones_factura', sa.UnicodeText().with_variant(sa.NVARCHAR(), 'mssql'), nullable=True),
    sa.Column('fecha_inicio_transmision', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=False),
    sa.Column('fecha_fin_transmision', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=False),
    sa.Column('fecha_factura', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=False),
    sa.Column('fecha_entrega_factura', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=True),
    sa.Column('subtotal_factura', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('iva_factura', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_factura', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cuenta_contable_id', sa.Uuid(), nullable=False),
    sa.Column('metodo_pago_clave', sa.Unicode(length=20), nullable=False),
    sa.Column('info_cuenta_pago', sa.UnicodeText().with_variant(sa.NVARCHAR(), 'mssql'), nullable=True),
    sa.Column('layout_factura', sa.Unicode(length=200), nullable=True),
    sa.Column('estado_facturacion', sa.Unicode(length=30), nullable=False),
    sa.Column('folio_fiscal_sat', sa.Unicode(length=50), nullable=True),
    sa.Column('fecha_timbrado', sa.Date().with_variant(sa.DATE(), 'mssql'), nullable=True),
    sa.Column('xml_path', sa.Unicode(length=500), nullable=True),
    sa.Column('pdf_path', sa.Unicode(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("estado_facturacion IN ('preparada', 'enviada_a_timbrado', 'timbrada', 'entregada', 'cobrada', 'cancelada')", name='ck_factura_cliente_estado'),
    sa.CheckConstraint('ROUND(iva_factura, 2) = ROUND(subtotal_factura * 0.16, 2)', name='ck_factura_cliente_iva_calculado'),
    sa.CheckConstraint('ROUND(total_factura, 2) = ROUND(subtotal_factura + iva_factura, 2)', name='ck_factura_cliente_total_suma'),
    sa.CheckConstraint('fecha_fin_transmision >= fecha_inicio_transmision', name='ck_factura_cliente_periodo'),
    sa.CheckConstraint('iva_factura >= 0', name='ck_factura_cliente_iva'),
    sa.CheckConstraint('subtotal_factura >= 0', name='ck_factura_cliente_subtotal'),
    sa.CheckConstraint('total_factura >= 0', name='ck_factura_cliente_total'),
    sa.ForeignKeyConstraint(['agencia_id'], ['agencia.agencia_id'], name='fk_factura_cliente_agencia', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['anunciante_id'], ['anunciante.anunciante_id'], name='fk_factura_cliente_anunciante', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['created_by'], ['usuario.usuario_id'], name='fk_factura_cliente_created_by', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['cuenta_contable_id'], ['cuenta_contable.cuenta_contable_id'], name='fk_factura_cliente_cuenta', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['empresa_facturadora_id'], ['empresa_facturadora.empresa_facturadora_id'], name='fk_factura_cliente_empresa', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['factura_relacionada_id'], ['factura_cliente.factura_id'], name='fk_factura_cliente_relacionada', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['orden_id'], ['orden_cliente.orden_id'], name='fk_factura_cliente_orden', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('factura_id')
    )
    # 1:1 OC↔factura, pero solo entre facturas NO canceladas (ADR-047): así una OC cuya
    # factura se canceló puede volver a facturarse sin borrar el registro de la cancelada.
    # Índice FILTRADO en SQL Server / PARCIAL en SQLite: verificado que ambos motores lo
    # soportan y que SQLAlchemy emite el mismo DDL para los dos.
    op.create_index(
        'uq_factura_cliente_orden_vigente',
        'factura_cliente',
        ['orden_id'],
        unique=True,
        mssql_where=sa.text("estado_facturacion <> 'cancelada'"),
        sqlite_where=sa.text("estado_facturacion <> 'cancelada'"),
    )
    op.create_table('factura_afiliado_orden',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('factura_afiliado_id', sa.Uuid(), nullable=False),
    sa.Column('orden_estacion_id', sa.Uuid(), nullable=False),
    sa.Column('monto_asignado', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notas_asignacion', sa.UnicodeText().with_variant(sa.NVARCHAR(), 'mssql'), nullable=True),
    sa.CheckConstraint('monto_asignado >= 0', name='ck_factura_afiliado_orden_monto'),
    sa.ForeignKeyConstraint(['factura_afiliado_id'], ['factura_afiliado.factura_afiliado_id'], name='fk_factura_afiliado_orden_factura', ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['orden_estacion_id'], ['orden_estacion.orden_estacion_id'], name='fk_factura_afiliado_orden_oe', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_afiliado_id', 'orden_estacion_id', name='uq_factura_afiliado_orden_factura_oe')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_factura_cliente_orden_vigente', table_name='factura_cliente')
    op.drop_table('factura_afiliado_orden')
    op.drop_table('factura_cliente')
    op.drop_table('factura_agencia')
    op.drop_table('costo_adicional')
    op.drop_table('factura_afiliado')
    # ### end Alembic commands ###
