"""f0 01 catalogos operativos

Revision ID: 7300e6f940a3
Revises: 
Create Date: 2026-07-01 19:07:39.998322
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# identificadores de revisión, usados por Alembic.
revision: str = '7300e6f940a3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plaza',
    sa.Column('plaza_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_plaza', sa.Unicode(length=120), nullable=False),
    sa.Column('estado', sa.Unicode(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.PrimaryKeyConstraint('plaza_id')
    )
    op.create_index(op.f('ix_plaza_nombre_plaza'), 'plaza', ['nombre_plaza'], unique=False)
    op.create_table('afiliado',
    sa.Column('afiliado_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_afiliado', sa.Unicode(length=160), nullable=False),
    sa.Column('razon_social_afiliado', sa.Unicode(length=200), nullable=False),
    sa.Column('rfc_afiliado', sa.Unicode(length=13), nullable=False),
    sa.Column('plaza_id', sa.Uuid(), nullable=False),
    sa.Column('contacto_nombre', sa.Unicode(length=160), nullable=True),
    sa.Column('contacto_email', sa.Unicode(length=160), nullable=True),
    sa.Column('contacto_telefono', sa.Unicode(length=40), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.ForeignKeyConstraint(['plaza_id'], ['plaza.plaza_id'], ),
    sa.PrimaryKeyConstraint('afiliado_id')
    )
    op.create_index(op.f('ix_afiliado_nombre_afiliado'), 'afiliado', ['nombre_afiliado'], unique=False)
    op.create_index(op.f('ix_afiliado_plaza_id'), 'afiliado', ['plaza_id'], unique=False)
    op.create_index(op.f('ix_afiliado_rfc_afiliado'), 'afiliado', ['rfc_afiliado'], unique=True)
    op.create_table('estacion',
    sa.Column('estacion_id', sa.Uuid(), nullable=False),
    sa.Column('afiliado_id', sa.Uuid(), nullable=False),
    sa.Column('plaza_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_estacion', sa.Unicode(length=120), nullable=False),
    sa.Column('frecuencia', sa.Unicode(length=40), nullable=True),
    sa.Column('tipo_senal', sa.Unicode(length=4), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=False),
    sa.Column('updated_at', sa.DateTime().with_variant(mssql.DATETIME2(), 'mssql'), nullable=True),
    sa.CheckConstraint("tipo_senal IN ('fm', 'am', 'tv')", name='ck_estacion_tipo_senal'),
    sa.ForeignKeyConstraint(['afiliado_id'], ['afiliado.afiliado_id'], ),
    sa.ForeignKeyConstraint(['plaza_id'], ['plaza.plaza_id'], ),
    sa.PrimaryKeyConstraint('estacion_id')
    )
    op.create_index(op.f('ix_estacion_afiliado_id'), 'estacion', ['afiliado_id'], unique=False)
    op.create_index(op.f('ix_estacion_nombre_estacion'), 'estacion', ['nombre_estacion'], unique=False)
    op.create_index(op.f('ix_estacion_plaza_id'), 'estacion', ['plaza_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estacion_plaza_id'), table_name='estacion')
    op.drop_index(op.f('ix_estacion_nombre_estacion'), table_name='estacion')
    op.drop_index(op.f('ix_estacion_afiliado_id'), table_name='estacion')
    op.drop_table('estacion')
    op.drop_index(op.f('ix_afiliado_rfc_afiliado'), table_name='afiliado')
    op.drop_index(op.f('ix_afiliado_plaza_id'), table_name='afiliado')
    op.drop_index(op.f('ix_afiliado_nombre_afiliado'), table_name='afiliado')
    op.drop_table('afiliado')
    op.drop_index(op.f('ix_plaza_nombre_plaza'), table_name='plaza')
    op.drop_table('plaza')
    # ### end Alembic commands ###
